/**

 * Form Editform

 *

 * @copyright: Copyright (C) 2005-2016  Media A-Team, Inc. - All rights reserved.

 * @license:   GNU/GPL http://www.gnu.org/copyleft/gpl.html

 */
define(["jquery","fab/fabrik"],(function(t,e){"use strict";return new Class({Implements:[Events],options:{formid:0,table:0,elements:""},initialize:function(e,n){if(n.showEditForm){const{baseUrl:e}=n,{elements:i}=n,r=document.querySelector(".fabrikForm");var a=document.createElement("div");a.innerHTML=this.htmlModal(e),r.appendChild(a);const o=Array.from(document.querySelectorAll("label"));o.forEach((t=>{Object.keys(i).forEach((e=>{t.getAttribute("for")===i[e].HTMLids[0]&&(t.idElement=e)}))}));const l=t=>{var n=document.createElement("i");n.className="icon-edit",n.style="cursor: pointer; ",n.title="Alterar este elemento",n.addEventListener("click",(function(){const n=`${e}administrator/index.php?option=com_fabrik&view=element&layout=edit&id=${t.idElement}`;document.querySelector("#iframe-url").src=n}));var a=document.createElement("a");return a.rel="modal",a.href="#janela",a.appendChild(n),a};o.forEach((t=>{t.appendChild(l(t))})),t("a[rel=modal]").click((function(e){e.preventDefault();var n=t(this).attr("href"),a=t(document).height(),i=t(window).width();t("#mascara").css({width:i,height:a}),t("#mascara").fadeIn(200),t("#mascara").fadeTo("slow",.2);var r=t(window).width()/2-t(n).width()/2,o=t(window).height()/2-t(n).height()/2;t(n).css({left:r,top:o}),t(n).show()})),t("#mascara").click((function(){t(this).fadeOut("slow"),t(".window").fadeOut("slow")})),t(".fechar").click((function(e){e.preventDefault(),t("#mascara").fadeOut(200,"linear"),t(".window").fadeOut(200,"linear"),window.location.reload()}))}},htmlModal:function(t){return`\n\t\t\t<style>\n\t\t\t\t.window{\t\n\t\t\t\t\tdisplay: none;\n\t\t\t\t\twidth: 90%;\n\t\t\t\t\theight: 90vh;\n\t\t\t\t\tposition: absolute;\n\t\t\t\t\tbackground: #FFF ;\n\t\t\t\t\tleft: 0;\n\t\t\t\t\ttop:0;\n\t\t\t\t\tz-index: 9900;\n\t\t\t\t\tborder-radius: 10px;\t\t\t\n\t\t\t\t}\n\t\t\t\t\n\t\t\t\t#mascara{\t\t\t\t\n\t\t\t\t\tdisplay: none;\n\t\t\t\t\tposition: absolute;\n\t\t\t\t\topacity: 0.2;\n\t\t\t\t\tbackground: #000 ;\n\t\t\t\t\tleft: 0;\n\t\t\t\t\ttop:0;\n\t\t\t\t\tz-index: 9000;\t\t\t\n\t\t\t\t}\n\t\t\t\t\n\t\t\t\t.fechar{\t\t\t\t\n\t\t\t\t\tdisplay: block;\n\t\t\t\t\ttext-align: right;\n\t\t\t\t}\n\t\t\t</style>\n\t\t\t\x3c!-- <a href="#janela" rel="Modal">Abrir Janela Modal</a> --\x3e\n\t\t\t<div class="window" id="janela">\n\t\t\t\t<a href="#" class="fechar" style="margin-right:10px; ">X Fechar</a>\n\t\t\t\t<iframe id="iframe-url" height="100%" width="100%" src="${t}/administrator/index.php?option=com_fabrik&view=element&layout=edit" title="W3Schools Free Online Web Tutorials"></iframe>\n\t\t\t</div>\n\t\t\t<div id="mascara"></div>\n\t\t\t`}})}));